<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="In this page, we analyze our data in more depth using more sophisticated statistical techniques.">

<title>MA [46]15 Final Project - Team 4 - Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project - Team 4</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">MA415 Team 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html" rel="" target="">
 <span class="menu-text">Big Picture</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" rel="" target="" aria-current="page">
 <span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section-1-exploratory-data-analysis-of-education-statistics" id="toc-section-1-exploratory-data-analysis-of-education-statistics" class="nav-link active" data-scroll-target="#section-1-exploratory-data-analysis-of-education-statistics">Section 1: Exploratory Data Analysis of Education Statistics</a>
  <ul class="collapse">
  <li><a href="#section-1.1-pisa-scores-and-literacy-rates" id="toc-section-1.1-pisa-scores-and-literacy-rates" class="nav-link" data-scroll-target="#section-1.1-pisa-scores-and-literacy-rates">Section 1.1: PISA Scores and Literacy Rates</a></li>
  <li><a href="#section-1.2-percentage-of-people-who-did-not-complete-primary-school" id="toc-section-1.2-percentage-of-people-who-did-not-complete-primary-school" class="nav-link" data-scroll-target="#section-1.2-percentage-of-people-who-did-not-complete-primary-school">Section 1.2: Percentage of People who did not Complete Primary School</a></li>
  <li><a href="#section-1.3-years-of-edcuation" id="toc-section-1.3-years-of-edcuation" class="nav-link" data-scroll-target="#section-1.3-years-of-edcuation">Section 1.3: Years of Edcuation</a></li>
  <li><a href="#section-1.4-percent-of-students-not-in-school" id="toc-section-1.4-percent-of-students-not-in-school" class="nav-link" data-scroll-target="#section-1.4-percent-of-students-not-in-school">Section 1.4: Percent of Students not in School</a></li>
  <li><a href="#section-1.5-top-countries-in-each-section" id="toc-section-1.5-top-countries-in-each-section" class="nav-link" data-scroll-target="#section-1.5-top-countries-in-each-section">Section 1.5: Top countries in each section</a></li>
  </ul></li>
  <li><a href="#section-2-statistical-modeling" id="toc-section-2-statistical-modeling" class="nav-link" data-scroll-target="#section-2-statistical-modeling">Section 2: Statistical Modeling</a>
  <ul class="collapse">
  <li><a href="#section-2.1-model1" id="toc-section-2.1-model1" class="nav-link" data-scroll-target="#section-2.1-model1">Section 2.1: Model1</a>
  <ul class="collapse">
  <li><a href="#section-2.1.1-model1-formula" id="toc-section-2.1.1-model1-formula" class="nav-link" data-scroll-target="#section-2.1.1-model1-formula">Section 2.1.1: Model1 Formula</a></li>
  <li><a href="#section-2.1.2-model1-result-analysis" id="toc-section-2.1.2-model1-result-analysis" class="nav-link" data-scroll-target="#section-2.1.2-model1-result-analysis">Section 2.1.2: Model1 Result Analysis</a></li>
  <li><a href="#section-2.1.3-model1-conclusion" id="toc-section-2.1.3-model1-conclusion" class="nav-link" data-scroll-target="#section-2.1.3-model1-conclusion">Section 2.1.3: Model1 Conclusion</a></li>
  </ul></li>
  <li><a href="#section-2.2-model2" id="toc-section-2.2-model2" class="nav-link" data-scroll-target="#section-2.2-model2">Section 2.2: Model2</a>
  <ul class="collapse">
  <li><a href="#section-2.2.1-model2-formula" id="toc-section-2.2.1-model2-formula" class="nav-link" data-scroll-target="#section-2.2.1-model2-formula">Section 2.2.1: Model2 Formula</a></li>
  <li><a href="#section-2.2.2-model2-result-analysis" id="toc-section-2.2.2-model2-result-analysis" class="nav-link" data-scroll-target="#section-2.2.2-model2-result-analysis">Section 2.2.2: Model2 Result Analysis</a></li>
  <li><a href="#section-2.2.3-model2-conclusion" id="toc-section-2.2.3-model2-conclusion" class="nav-link" data-scroll-target="#section-2.2.3-model2-conclusion">Section 2.2.3: Model2 Conclusion</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#section-3-limitations" id="toc-section-3-limitations" class="nav-link" data-scroll-target="#section-3-limitations">Section 3: Limitations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    In this page, we analyze our data in more depth using more sophisticated statistical techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="https://habitatbroward.org/wp-content/uploads/2020/01/10-Benefits-Showing-Why-Education-Is-Important-to-Our-Society.jpg" class="img-fluid"></p>
<section id="section-1-exploratory-data-analysis-of-education-statistics" class="level1">
<h1>Section 1: Exploratory Data Analysis of Education Statistics</h1>
<p>Driven by the increasing interest in global education disparities, our team has decided to explore the educational landscape across various countries around the world. Education is a cornerstone of societal development, and by examining comprehensive datasets (please see the data tab to read more about our datasets), we aim to uncover the factors that contribute to education outcomes and identify disparities that may hinder equitable access to quality education. Our project seeks to provide insights that not can potentially inform policymakers, educators, and stakeholders about the key elements influencing educational success.</p>
<p>Our project begins with section 1, where we will identify educational trends by the continent and attempt to answer <strong><em>why</em></strong> these continents are the way they are by exploring different regions and countries within each continent.</p>
<p>In section 2, we will model our data with different statistical models, and uncover insights that are harder to identify on the surface.</p>
<p>Lastly, in section 3, we will discuss the shortcomings of our analysis.</p>
<section id="section-1.1-pisa-scores-and-literacy-rates" class="level3">
<h3 class="anchored" data-anchor-id="section-1.1-pisa-scores-and-literacy-rates">Section 1.1: PISA Scores and Literacy Rates</h3>
<p>The first step to understanding economic disparities is to get a general understanding of what parts of the world generally tend to have better education than others. There are multiple ways of measuring this, but a reliable way to measure this is with PISA scores and literacy rates. Both of these metrics serve as standardized bench marks for the whole world!</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/literacy-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It is clear that in terms of PISA scores, Oceania and Europe perform the best, while Africa performed the worst, and in terms of literacy rate, all of the continents performed relatively equally while Africa performed the worst again. Now that you have a general understanding of where education is better and where education is worse, we can now get into more specific statistics.</p>
</section>
<section id="section-1.2-percentage-of-people-who-did-not-complete-primary-school" class="level3">
<h3 class="anchored" data-anchor-id="section-1.2-percentage-of-people-who-did-not-complete-primary-school">Section 1.2: Percentage of People who did not Complete Primary School</h3>
<p>The next step of analyzing education around the world was to simply look at the percentage of children and young people aged 3-5 years above primary school graduation age who have completed primary school.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/priary school completion 3-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see, Europe consistently ranks significantly higher than all of the other continents, while North America, South America, and Asia rank below Europe but higher than Africa. However, if we take a deeper look into the sub regions of Africa, we find some interesting outcomes.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/north africa primary completion-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/sub-saharan africa primary school completion-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see, when looking at the percentage of people who finish primary school, the percentages are significantly lower for the Sub-Saharan African countries compared to the Northern African countries. It seems like Sub-Saharan Africa may be the reason Africa shows up so low in many of the plots in the first section. In fact, Northern Africa seems to be on par in terms of primary school completion rate when compared to the rest of the continents in the world, but Sub-Sahara Africa does not seem to be on par. This difference in regions suggests that much attention should actually be directed towards Sub-Saharan Africa rather than Africa as a whole.</p>
<p>The good news is that all countries seem to have a slow yet steady increase in their primary school completion rate which is great to see.</p>
<p>The next step is to analyze the mean years of education of each region.</p>
</section>
<section id="section-1.3-years-of-edcuation" class="level3">
<h3 class="anchored" data-anchor-id="section-1.3-years-of-edcuation">Section 1.3: Years of Edcuation</h3>
<p>After just two sections, it seems that there is a trend: Europe tends to have the “best education” while Africa seems to have “the worst education.” We will now explore average years of education as another measure of education.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/mean years of education-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This graph shows a similar result to the other graphs: Africa again ranks as the lowest. However, there are many reasons why this may be the case. For example, if we look mean years of education in rural areas vs.&nbsp;mean years of education in urban areas, we see that Africa has the largest discrepancy in this area.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/rural vs urban for mean years of education-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This large discrepancy in specifically Africa is so large that it could be bringing Africa down in total mean years of education. However, it is certainly worth noting that Africa’s urban mean years of education is still not to par with most other regions in the world, meaning Africa as a whole needs improvement in their education system.</p>
<p>The next step is to look at learning achievements as a mesure of level of education.</p>
</section>
<section id="section-1.4-percent-of-students-not-in-school" class="level3">
<h3 class="anchored" data-anchor-id="section-1.4-percent-of-students-not-in-school">Section 1.4: Percent of Students not in School</h3>
<p>Another important metric of education is the percentage of students who are and are not in school. Regardless of academic outcome (GPA, test scores, etc.) It is incredibly important that younger people are even attending school to begin with. UNESCO provides data on attendance rates for primary school, lower secondary school, and upper secondary school.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/per. of people not in lowsec school-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see, Africa has the highest percentage of not attending school for all three categories, and Europe has the lowest. A surprising result in this metric is how South America has the second lowest non-attendance rate which is good. While they ranked lower in other metrics such as their test scores, it is clear that at the very least, South America <strong><em>is</em></strong> doing a good job getting their students to at least attend school. Let’s break this down further by looking at Rural vs.&nbsp;Urban areas.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/rural vs urban-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Similar to what we observed in section 1.3 the rural areas perform worse in this metric; however, it is worth noting that rural areas are performing even worse in this metric than the mean years of education section. For example, in North America and South America, the Rural non-attendance rate is almost half of non-attendance rate for urban areas. This implies that Rural areas need significantly more work than non-rural areas. Let’s now break it down by gender.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/gender-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that The Americas and Europe do a good job keeping their kids in school, but North America’s rate is high in general. It seems like it has the second or third highest average rate out of all the continents which is a bit concerning. While they are doing a good job being equal among sex, they are not doing a great job keeping kids in school in general. On the other hand, Africa, Asia, and Oceania have a considerable discrepancy in rate sex. This suggests that these continents may have some sexism in their education systems.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/facet-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When looking at discrepancies across each country in each continent, it is clear that every continent has multiple countries that have extremely high rates of not being in school as well as multiple countries that have extremely low rates. While some continents have more countries with higher rates than others, what is clear that every continent has countries with poor education.</p>
</section>
<section id="section-1.5-top-countries-in-each-section" class="level3">
<h3 class="anchored" data-anchor-id="section-1.5-top-countries-in-each-section">Section 1.5: Top countries in each section</h3>
<p>We have analyzed continents as a whole, but now lets analyze each continent’s lowest performers in each category.</p>
<section id="bottom-3-countries-in-each-continent-with-lowest-primary-school-completion-rate" class="level4">
<h4 class="anchored" data-anchor-id="bottom-3-countries-in-each-continent-with-lowest-primary-school-completion-rate">Bottom 3 countries in each continent with lowest primary school completion rate</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">region</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">Primary School Completion Rate</th>
<th style="text-align: right;">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Liberia</td>
<td style="text-align: right;">0.2291407</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">0.2348941</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Chad</td>
<td style="text-align: right;">0.2350572</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">0.5104556</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">0.5843212</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Cambodia</td>
<td style="text-align: right;">0.6162612</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">0.9742778</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Montenegro</td>
<td style="text-align: right;">0.9898302</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Serbia</td>
<td style="text-align: right;">0.9959805</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Haiti</td>
<td style="text-align: right;">0.3944480</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">0.6732015</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: right;">0.6776326</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Vanuatu</td>
<td style="text-align: right;">0.8169209</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Kiribati</td>
<td style="text-align: right;">0.9467611</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Fiji</td>
<td style="text-align: right;">0.9874556</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Suriname</td>
<td style="text-align: right;">0.8031490</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">0.8113292</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">0.8799102</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="bottom-3-countries-in-each-continent-with-lowest-mean-years-of-education" class="level4">
<h4 class="anchored" data-anchor-id="bottom-3-countries-in-each-continent-with-lowest-mean-years-of-education">Bottom 3 countries in each continent with lowest mean years of education</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">region</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">Mean Years of Education</th>
<th style="text-align: right;">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">1.808006</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Burkina Faso</td>
<td style="text-align: right;">2.347315</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Mali</td>
<td style="text-align: right;">2.410002</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">4.547361</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Nepal</td>
<td style="text-align: right;">5.895463</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">6.002957</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">10.390306</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Serbia</td>
<td style="text-align: right;">13.655235</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Ukraine</td>
<td style="text-align: right;">13.874593</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">6.572728</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Haiti</td>
<td style="text-align: right;">6.812426</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Honduras</td>
<td style="text-align: right;">6.991532</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">12.417176</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Fiji</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Kiribati</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Guyana</td>
<td style="text-align: right;">9.512641</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">9.540023</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">9.931102</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="top-3-countries-in-each-continent-of-percentage-of-people-not-in-primary-school" class="level4">
<h4 class="anchored" data-anchor-id="top-3-countries-in-each-continent-of-percentage-of-people-not-in-primary-school">Top 3 Countries in Each Continent of Percentage of People Not in Primary School</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">region</th>
<th style="text-align: left;">country</th>
<th style="text-align: right;">Non-attendance Rate</th>
<th style="text-align: right;">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">South Sudan</td>
<td style="text-align: right;">0.7504588</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Liberia</td>
<td style="text-align: right;">0.6322090</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Somalia</td>
<td style="text-align: right;">0.5401778</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">0.3667935</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">0.3079629</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Timor-Leste</td>
<td style="text-align: right;">0.2362871</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Belarus</td>
<td style="text-align: right;">0.0826894</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">0.0667680</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Ukraine</td>
<td style="text-align: right;">0.0610106</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Haiti</td>
<td style="text-align: right;">0.1998055</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">0.0967366</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: right;">0.0949205</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Vanuatu</td>
<td style="text-align: right;">0.1354130</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Kiribati</td>
<td style="text-align: right;">0.0316477</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">Tonga</td>
<td style="text-align: right;">0.0274431</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">0.0621273</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">0.0598511</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">0.0381532</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Some countries that appear multiple times on these tables are Niger, Pakistan, Afghanistan, and Haiti.</p>
</section>
</section>
</section>
<section id="section-2-statistical-modeling" class="level1">
<h1>Section 2: Statistical Modeling</h1>
<p>Thesis: African areas have poor educational resources compared with other regions in the World. Our investigation will delve into the factors contributing to poor educational resources, particularly in African regions, and will evaluate whether Africa indeed has the most challenging educational conditions compared to the rest of the world.</p>
<section id="section-2.1-model1" class="level2">
<h2 class="anchored" data-anchor-id="section-2.1-model1">Section 2.1: Model1</h2>
<p>Hypothesis 1: Factors that will affect the lower secondary school completion rate: primary school completion rate_v2(young people who are 3-5 ages above the normal primary graduation age[prolly neagtively affect the lower secondary school completion rate]), big_region, wealth, gender, and Urbanicity</p>
<p>Expectation: comp_prim_v2_m will positively affect comp_lowsec_v2_m. In region of Africa, the area of rural, the gender of female, or the quintile 1 in Wealth will negatively affect comp_lowsec_v2_m.</p>
<p>-Continuous variable: comp_prim_v2_m</p>
<p>-Categorical variable: wealth(by level 1-5), sex(female/male), region(by continents), Location(=urbanicity by rural/urban)</p>
<section id="original-model1" class="level4">
<h4 class="anchored" data-anchor-id="original-model1">Original Model1</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = comp_lowsec_v2_m ~ as.factor(region) + as.factor(Location) + 
    as.factor(Sex) + as.factor(Wealth) + comp_prim_v2_m, data = Location_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.67342 -0.07977  0.02010  0.09152  0.39425 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -0.232695   0.007489 -31.070  &lt; 2e-16 ***
as.factor(region)Asia           0.092947   0.006050  15.362  &lt; 2e-16 ***
as.factor(region)Europe         0.198130   0.014221  13.933  &lt; 2e-16 ***
as.factor(region)North America  0.011440   0.007802   1.466 0.142649    
as.factor(region)Oceania        0.143052   0.037197   3.846 0.000122 ***
as.factor(region)South America  0.140285   0.007011  20.010  &lt; 2e-16 ***
as.factor(Location)Urban        0.020791   0.004415   4.710 2.57e-06 ***
as.factor(Sex)Male              0.003602   0.004164   0.865 0.387033    
as.factor(Wealth)Quintile 2     0.002351   0.007122   0.330 0.741322    
as.factor(Wealth)Quintile 3     0.009989   0.007108   1.405 0.160043    
as.factor(Wealth)Quintile 4     0.040039   0.007209   5.554 2.99e-08 ***
as.factor(Wealth)Quintile 5     0.096784   0.007521  12.869  &lt; 2e-16 ***
comp_prim_v2_m                  0.940660   0.010707  87.856  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1273 on 3726 degrees of freedom
  (28612 observations deleted due to missingness)
Multiple R-squared:  0.853, Adjusted R-squared:  0.8525 
F-statistic:  1802 on 12 and 3726 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                        GVIF Df GVIF^(1/(2*Df))
as.factor(region)   1.683944  5        1.053496
as.factor(Location) 1.124812  1        1.060572
as.factor(Sex)      1.000401  1        1.000201
as.factor(Wealth)   1.285657  4        1.031907
comp_prim_v2_m      1.931383  1        1.389742</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/original model 1-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/original model 1-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The residuals plot does not seem randomly distributed, so we decide to do some transformations on the variables to meet the assumptions of normality.</p>
</section>
<section id="normality-and-transformation" class="level4">
<h4 class="anchored" data-anchor-id="normality-and-transformation">Normality and Transformation</h4>
<p>We have tried to make the transformation on the response variable which does not seem normally distributed because, based on the left plot, the distribution left skewed severely. After different trials on the response variable, we finally applied the <strong>square root arcsine transformation</strong>, and we got the approximately normal histogram, shown by the right side of the plot.</p>
</section>
<section id="model-after-transformation" class="level4">
<h4 class="anchored" data-anchor-id="model-after-transformation">Model after Transformation</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = asin(sqrt(Location_data$comp_lowsec_v2_m)) ~ as.factor(region) + 
    as.factor(Location) + as.factor(Wealth) + as.factor(Sex) + 
    comp_prim_v2_m, data = Location_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.78259 -0.10385  0.01225  0.10890  0.50532 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -0.133804   0.009522 -14.052  &lt; 2e-16 ***
as.factor(region)Asia           0.122669   0.007692  15.947  &lt; 2e-16 ***
as.factor(region)Europe         0.345051   0.018080  19.085  &lt; 2e-16 ***
as.factor(region)North America  0.018736   0.009920   1.889 0.058995 .  
as.factor(region)Oceania        0.170825   0.047292   3.612 0.000308 ***
as.factor(region)South America  0.174104   0.008913  19.533  &lt; 2e-16 ***
as.factor(Location)Urban        0.031223   0.005613   5.563 2.84e-08 ***
as.factor(Wealth)Quintile 2     0.006059   0.009055   0.669 0.503466    
as.factor(Wealth)Quintile 3     0.017626   0.009038   1.950 0.051220 .  
as.factor(Wealth)Quintile 4     0.055694   0.009166   6.076 1.35e-09 ***
as.factor(Wealth)Quintile 5     0.132178   0.009562  13.824  &lt; 2e-16 ***
as.factor(Sex)Male              0.007044   0.005294   1.331 0.183381    
comp_prim_v2_m                  1.167443   0.013613  85.762  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1618 on 3726 degrees of freedom
  (28612 observations deleted due to missingness)
Multiple R-squared:  0.8514,    Adjusted R-squared:  0.8509 
F-statistic:  1779 on 12 and 3726 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/model 1 after transformation-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/model 1 after transformation-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After applying <strong>Arcsine Square Root transformation</strong> on the model, we made the square root of the standardized residuals plot to see if it met the assumption of homoscedasticity, which indeed improved a lot.</p>
</section>
<section id="section-2.1.1-model1-formula" class="level3">
<h3 class="anchored" data-anchor-id="section-2.1.1-model1-formula">Section 2.1.1: Model1 Formula</h3>
<p>asin(sqrt(Location_data$comp_lowsec_v2_m)) = b0 + b1 x region(Africa vs Asia) + b2 x region(Africa vs Europe) + b3 x region(Africa vs Oceania) + b3 x region(Africa vs South America) + b4 x Location(urban vs rural) + b5 x Wealth(Quintile 1 vs Quintile 4) + b6 x Wealth(Quintile 1 vs Quintile 5) + b7 x comp_prim_v2_m</p>
</section>
<section id="section-2.1.2-model1-result-analysis" class="level3">
<h3 class="anchored" data-anchor-id="section-2.1.2-model1-result-analysis">Section 2.1.2: Model1 Result Analysis</h3>
<p>Result Analysis:</p>
<p>1) The model’s intercept is negative, suggesting that the baseline group for region, location, sex, and wealth has a negative association with the completion rate for lower secondary education.</p>
<p>2) The region variable has several levels. Compared to the baseline of Africa as the reference category, all other regions (Asia, Europe, North America, Oceania, South America) show a positive association with lower secondary completion rates. To explain the association toward the response variable, I will provide an example. For the coefficient of 0.123 for Asia: This means that, compared to Africa, being in the region of Asia is associated with an average increase in the lower secondary completion rates by 0.123 units. Since the region of Africa is the baseline, and its association with all other region is positive, so we can conclude that being in Africa will have the lowest lower-secondary completion rate compared to other regions. And the significance is indicated by the p-value that is smaller than 0.05.</p>
<p>3) Urban locations have a positive coefficient, indicating that being in an urban location is associated with higher secondary completion rates compared to rural locations.</p>
<p>4) Sex does not seem to be a significant predictor, as the coefficient for males is small and not statistically significant (p-value &gt; 0.05).</p>
<p>5) Wealth shows a strong positive association with lower secondary completion. As wealth quintiles increase, there’s a corresponding significant increase in the completion rates, with the highest quintile (Quintile 5) having the largest coefficient.</p>
<p>6) The comp_prim_v2_m variable has a large positive coefficient, indicating a strong association with higher rates of lower secondary completion.</p>
<p>7) The adjusted R-squared is 0.8509, indicating a good fit even after adjusting for the number of predictors.</p>
<p>8) The F-statistic is very high, and the associated p-value is less than 0.001, suggesting the model is statistically significant.</p>
</section>
<section id="section-2.1.3-model1-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="section-2.1.3-model1-conclusion">Section 2.1.3: Model1 Conclusion</h3>
<p>The R-squared is 0.8509, and the vif shows that there is no collinearity between predictors. We will remove the predictor of “sex” from the mode because of insignificance indicated by p-value higher than 0.05. Finally, being in the region of Africa, being in the location of rural area, and staying in the lower wealth level will negatively influence the secondary education completion. And the high primary education completion will positively affect the secondary education completion rate.</p>
</section>
</section>
<section id="section-2.2-model2" class="level2">
<h2 class="anchored" data-anchor-id="section-2.2-model2">Section 2.2: Model2</h2>
<p>Hypothesis 2: Factors that will affect literacy_1524_m (Percentage of young people aged 15‐24 who can read a simple sentence): comp_prim_1524_no (# of young people aged 15-24 completed primary school), preschool_3_no (# of 3 to 4 year olds attending any type of pre–primary education programme), region, wealth.</p>
<p>Expectation: The predictors of either comp_prim_1524_no or preschool_3_no will negatively affect literacy_1524_m. Urban region will increase literacy_1524_m, and higher level of wealth will postively affect the literacy_1524_m as well.</p>
<p>-Continuous variable: comp_prim_1524_no, preschool_3_no</p>
<p>-Categorical variable: wealth(by level 1-5), region(by continents)</p>
<section id="original-model-2" class="level4">
<h4 class="anchored" data-anchor-id="original-model-2">Original Model 2</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = literacy_1524_no ~ as.factor(region) + as.factor(Wealth) + 
    edu2_2024_no + preschool_3_no, data = Location_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1903.48  -298.65   -34.83   212.14  3111.19 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -176.8065    82.7822  -2.136 0.033193 *  
as.factor(region)Asia           514.8999    62.2549   8.271 1.28e-15 ***
as.factor(region)Europe         616.8468    78.5480   7.853 2.61e-14 ***
as.factor(region)North America  253.9103   101.4412   2.503 0.012640 *  
as.factor(region)South America   68.7070   107.2218   0.641 0.521958    
as.factor(Wealth)Quintile 2      44.1101    83.1961   0.530 0.596219    
as.factor(Wealth)Quintile 3     158.7777    83.1703   1.909 0.056841 .  
as.factor(Wealth)Quintile 4     301.1526    85.1746   3.536 0.000446 ***
as.factor(Wealth)Quintile 5     701.4635    90.5896   7.743 5.65e-14 ***
edu2_2024_no                      2.2464     0.1267  17.728  &lt; 2e-16 ***
preschool_3_no                    0.6760     0.1764   3.832 0.000144 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 559.2 on 487 degrees of freedom
  (31853 observations deleted due to missingness)
Multiple R-squared:  0.7265,    Adjusted R-squared:  0.7208 
F-statistic: 129.3 on 10 and 487 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      GVIF Df GVIF^(1/(2*Df))
as.factor(region) 1.261002  4        1.029413
as.factor(Wealth) 1.214545  4        1.024594
edu2_2024_no      2.415127  1        1.554068
preschool_3_no    2.405951  1        1.551113</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/original model 2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/original model 2-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="normality-and-transformation-1" class="level4">
<h4 class="anchored" data-anchor-id="normality-and-transformation-1">Normality and Transformation</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/normality check-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We decided to apply a logarithmic transformation to the response variable to achieve a more normal distribution in the histogram. This transformation significantly improved the original distribution, which was severely right-skewed. After the transformation, the data exhibited a more normal distribution, as evidenced by the more evenly distributed frequencies.</p>
</section>
<section id="model-2-after-log-transformation" class="level4">
<h4 class="anchored" data-anchor-id="model-2-after-log-transformation">Model 2 After Log Transformation</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = literacy_1524_no ~ as.factor(region) + as.factor(Wealth) + 
    edu2_2024_no + preschool_3_no, data = Location_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1903.48  -298.65   -34.83   212.14  3111.19 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -176.8065    82.7822  -2.136 0.033193 *  
as.factor(region)Asia           514.8999    62.2549   8.271 1.28e-15 ***
as.factor(region)Europe         616.8468    78.5480   7.853 2.61e-14 ***
as.factor(region)North America  253.9103   101.4412   2.503 0.012640 *  
as.factor(region)South America   68.7070   107.2218   0.641 0.521958    
as.factor(Wealth)Quintile 2      44.1101    83.1961   0.530 0.596219    
as.factor(Wealth)Quintile 3     158.7777    83.1703   1.909 0.056841 .  
as.factor(Wealth)Quintile 4     301.1526    85.1746   3.536 0.000446 ***
as.factor(Wealth)Quintile 5     701.4635    90.5896   7.743 5.65e-14 ***
edu2_2024_no                      2.2464     0.1267  17.728  &lt; 2e-16 ***
preschool_3_no                    0.6760     0.1764   3.832 0.000144 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 559.2 on 487 degrees of freedom
  (31853 observations deleted due to missingness)
Multiple R-squared:  0.7265,    Adjusted R-squared:  0.7208 
F-statistic: 129.3 on 10 and 487 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      GVIF Df GVIF^(1/(2*Df))
as.factor(region) 1.261002  4        1.029413
as.factor(Wealth) 1.214545  4        1.024594
edu2_2024_no      2.415127  1        1.554068
preschool_3_no    2.405951  1        1.551113</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/Model 2 After Log Transformation-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/Model 2 After Log Transformation-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After Log Transformation on the y variable, the residual plots are more randomly distributed. And there is no multicollinearity. Thus, we will use this model as our final model.</p>
</section>
<section id="section-2.2.1-model2-formula" class="level3">
<h3 class="anchored" data-anchor-id="section-2.2.1-model2-formula">Section 2.2.1: Model2 Formula</h3>
<p>log (literacy_1524_no) = b0 + b1 x region(Africa vs Asia) + b2 x region(Africa vs Europe) + b3 x region(Africa vs North America) + b4 x Wealth(Quintile 1 vs Quintile 4) + b5 x Wealth(Quintile 1 vs Quintile 5) + b6 x edu2_2024_no + b7 x preschool_3_no</p>
</section>
<section id="section-2.2.2-model2-result-analysis" class="level3">
<h3 class="anchored" data-anchor-id="section-2.2.2-model2-result-analysis">Section 2.2.2: Model2 Result Analysis</h3>
<p>Result Analysis:</p>
<p>1) For the region variable: Asia has a positive coefficient (514.8999), meaning that, compared to the Africa region, it is associated with an increase in the dependent variable. Europe has an even higher positive coefficient (616.8468), indicating a stronger association compared to the Africa region than Asia. North America and South America also have positive coefficients, but the impact is less compared to Asia and Europe. The coefficients for regions are statistically significant except for South America (p-value &gt; 0.05).</p>
<p>2) Wealth quintiles show a gradient of increasing positive coefficients from Quintile 2 to Quintile 5, suggesting that as wealth increases, the dependent variable also increases. Quintile 5 has a particularly high coefficient, and the effects for Quintile 4 and Quintile 5 are statistically significant (p &lt; 0.01).</p>
<p>3) The variable edu2_2024_no has a very high positive coefficient (2424.4635), indicating a strong and statistically significant association with the dependent variable.</p>
<p>4) The preschool variable (preschool_3_no) has a small but statistically significant positive coefficient, indicating that an increase in this variable is associated with an increase in the dependent variable.</p>
<p>5) The model has a relatively high R-squared value of 0.7265, meaning approximately 72.65% of the variance in the dependent variable is explained by the model, indicating a good fit.</p>
<p>6) The F-statistic is very large, and the p-value is less than 0.001, suggesting that the model is highly statistically significant.</p>
</section>
<section id="section-2.2.3-model2-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="section-2.2.3-model2-conclusion">Section 2.2.3: Model2 Conclusion</h3>
<p>The R-squared is 0.7208, and the vif shows that there is no collinearity between predictors. We will remove the predictors that have the insignificance indicated by p-value higher than 0.05 from the model. In summary, being in the region of Africa and South America, or staying in the lower wealth level will negatively influence the secondary education completion. And the higher rate of attending pre-primary institution will positively affect the secondary education completion rate. However, an interetsing finding is that less than two years schooling can also increase the percentage of young people aged 15‐24 who can read a simple sentence. We could conduct further analysis on this relationship.</p>
</section>
</section>
</section>
<section id="section-3-limitations" class="level1">
<h1>Section 3: Limitations</h1>
<p>The dataset used in our project is extensive, resulting in a significant number of missing values despite rigorous efforts to filter them out. Additionally, our model has improved by thoroughly verifying the assumptions of normality, linearity, and homoscedasticity for all variables, and we did some transformations on the variable, such as arcsine square root transformation, which helped to meet the assumptions, but it makes the interpretation hard. Notably, our initial findings suggest that even less than two years of schooling can increase the percentage of young people who can read simple sentences. We may do extension project to explore the underlying factors and implications for this unexpected outcome.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>