---
title: "test"
editor: visual
---

```{r}
library(tidyverse)
library(tidymodels)
library(broom)
library(scales) # for the label_comma() function
```

```{r}
data <- read_csv('dataset/educ.csv')
continent <- read_csv('dataset/continents2.csv')
pisa <- read_csv('dataset/pisa-scores-by-country-2024.csv')
```

 

```{r}
#data
#continent
#pisa
```

```{r}
continent <- continent |>
  rename(
    country = name,
    sub_region = `sub-region`
  )

#continent
merged_data <- merge(data, continent, by = "country")
merged_data2 <- merge(merged_data, pisa, by = "country")
#merged_data
```

```{r}
afg <- data |>
  filter(iso_code == 'AFG')
afg
```

```{r}
grouped <- data |>
  group_by(iso_code, Sex) |>
  summarise(mean = mean(comp_prim_v2_m, na.rm = TRUE), count = n())

grouped


```

```{r}
grouped2 <- data |>
  group_by(iso_code) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            count = n())
grouped2
```

```{r}
grouped3 <- merged_data |>
  #filter(survey == 'DHS') |>
  #filter(region_group %in% c('Central and Southern Asia', 'Europe and Northern America', 'Sub-Saharan Africa')) |>
  group_by(`sub_region`, year) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = year, y = percent_people_not_in_primary_school, color = sub_region)) +
    geom_line()
grouped3
```

```{r}
grouped5 <- merged_data |>
  #filter(survey == 'DHS') |>
  #filter(region_group %in% c('Central and Southern Asia', 'Europe and Northern America', 'Sub-Saharan Africa')) |>
  group_by(`sub_region`, year) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = year, y = mean_primary_completion_rate, color = sub_region)) +
    geom_line()
grouped5
```

```{r}
grouped6 <- merged_data |>
  #filter(survey == 'DHS') |>
  #filter(region_group %in% c('Central and Southern Asia', 'Europe and Northern America', 'Sub-Saharan Africa')) |>
  group_by(region, year) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = year, y = mean_educ_years_20_24, color = region)) +
    geom_line()
grouped6
```

```{r}
grouped7 <- merged_data |>
  filter(sub_region %in% c('Northern Africa')) |>
  group_by(sub_region, Location) |>
  summarise(
    mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
    count = n()
  ) |>
  ggplot(
    aes(x = Location, y = mean_primary_completion_rate, fill = Location) 
  )+geom_col() +ylim(c(0,1)) + labs(
    title = 'Primary school completion rate of North Africans',
    subtitle = 'This is data includes i) children and young people 3-5 years above primary school graduation age and ii) young people aged 15-24 years, who have completed primary school',
    x = 'Location',
    y = 'Primary school completion rate'
  )

grouped7
```

```{r}
grouped8 <- merged_data |>
  filter(sub_region %in% c('Sub-Saharan Africa')) |>
  group_by(sub_region, Location) |>
  summarise(
    mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
    count = n()
  ) |>
  ggplot(
    aes(x = Location, y = mean_primary_completion_rate, fill = Location) 
  )+geom_col() +ylim(c(0,1)) + labs(
    title = 'Primary school completion rate of Sub-Saharan Africans',
    subtitle = 'This is data includes i) children and young people 3-5 years above primary school graduation age and ii) young people aged 15-24 years, who have completed primary school',
    x = 'Location',
    y = 'Primary school completion rate'
  )

grouped8
```

```{r}
grouped9 <- merged_data |>
  #filter(survey == 'DHS') |>
  filter(sub_region %in% c('Northern Africa')) |>
  group_by(iso_code) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = iso_code, y = mean_primary_completion_rate, fill = iso_code)) +
    geom_col() +ylim(c(0,1))
grouped9
```

```{r}
grouped10 <- merged_data |>
  #filter(survey == 'DHS') |>
  filter(sub_region %in% c('Latin America and the Caribbean')) |>
  group_by(iso_code) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = iso_code, y = mean_primary_completion_rate, fill = iso_code)) +
    geom_col() +ylim(c(0,1)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
grouped10
```

```{r}
grouped11 <- merged_data |>
  #filter(survey == 'DHS') |>
  filter(sub_region %in% c('Latin America and the Caribbean')) |>
  group_by(iso_code) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            obs_primary_completion_rate = sum(!is.na(comp_prim_v2_m)),
            percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
            count = n()
            ) |>
  ggplot(aes(x = iso_code, y = obs_primary_completion_rate, fill = iso_code)) + geom_col() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

grouped11
```

```{r}
lm_model <- 
  linear_reg() %>% 
  set_engine("lm")

grouped2 <- data |>
  group_by(iso_code) |>
  summarise(mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
            mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
            attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
            count = n()) |>
  ungroup()

grouped2

```

```{r}
lm_model <- 
  linear_reg() |> 
  set_engine("lm")

lm_form_fit <- 
  lm_model %>% 
  fit(mean_primary_completion_rate ~ mean_educ_years_20_24, data = grouped2)

lm_form_fit
```

```{r}
summary(lm_form_fit)
```

```{r}
broom::glance(lm_form_fit)
broom::augment(lm_form_fit, new_data = grouped2)
```

```{r}
ggplot(grouped2, aes(x = mean_educ_years_20_24, y=mean_primary_completion_rate)) + geom_point() + geom_smooth() + geom_smooth(method = 'lm', color = 'red')
```

`{r}lo} ggplot(   broom::augment(lm_form_fit, new_data =grouped2), aes(x = .pred, y = .resid)   ) +    geom_point(alpha = 0.45, style = 'O', size = 2.5) +    ylim(c(-1,1)) +    geom_line(y =   0, color = 'red')`

```{r}
pisa_summary <- merged_data2 |>
  group_by(country) |>
  summarise(
    mean_primary_completion_rate = mean(comp_prim_v2_m, na.rm = TRUE),
    obs_primary_completion_rate = sum(!is.na(comp_prim_v2_m)),
    percent_people_not_in_primary_school = mean(eduout_upsec_m, na.rm = TRUE),
    mean_educ_years_20_24 = mean(eduyears_2024_m, na.rm = TRUE),
    attend_higher_education = mean(attend_higher_1822_m, na.rm = TRUE),
    number_complete_prim_1524 = mean(comp_prim_1524_no, na.rm = TRUE),
    pisa_overall_mean = mean(OverallPisaScore2022),
    pisa_math_mean = mean(PISAScoresScienceScore2022),
    pisa_science_mean = mean(PISAScoresScienceScore2022),
    pisa_reading_mean = mean(PISAScoresReadingScore2022)
  )

pisa_summary
```

```{r}

# Assuming merged_data is your original data frame
americas_pisa_long <- merged_data2 %>%
  filter(region == 'Americas') %>%
  group_by(country) %>%
  summarise(
    pisa_overall_mean = mean(OverallPisaScore2022, na.rm = TRUE),
    pisa_math_mean = mean(PISAScoresMathScore2022, na.rm = TRUE), # Assuming you meant Math Score here
    pisa_science_mean = mean(PISAScoresScienceScore2022, na.rm = TRUE),
    pisa_reading_mean = mean(PISAScoresReadingScore2022, na.rm = TRUE)
  ) %>%
  pivot_longer(
    cols = starts_with("pisa_"),
    names_to = "score_type",
    values_to = "score"
  ) %>%
  mutate(score_type = factor(score_type, levels = c("pisa_overall_mean", "pisa_math_mean", "pisa_science_mean", "pisa_reading_mean")))

# Creating the plot
americas_pisa_plot <- americas_pisa_long %>%
  ggplot(aes(x = country, y = score, fill = score_type)) + 
  geom_col(position = "dodge") + 
  scale_y_continuous(labels = label_comma()) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "PISA Score", x = "Country", fill = "Score Type") +
  scale_fill_brewer(palette = "Pastel1") # Using a color palette for better visual distinction

americas_pisa_plot
```

```{r}
lm_form_fit2 <- 
  lm_model |> 
  fit(pisa_math_mean ~ mean_primary_completion_rate + percent_people_not_in_primary_school + mean_educ_years_20_24 + attend_higher_education + number_complete_prim_1524, data = pisa_summary)

lm_form_fit2

```

```{r}
broom::glance(lm_form_fit2)
broom::augment(lm_form_fit2, new_data = pisa_summary)
```

```{r}
lm_form_fit2 <- 
  lm_model |> 
  fit(pisa_overall_mean ~ mean_primary_completion_rate + percent_people_not_in_primary_school + mean_educ_years_20_24 + attend_higher_education + number_complete_prim_1524, data = pisa_summary)

lm_form_fit2

```
