---
title: "Blog Post 1: Potential Datasets"
author: "Team 4"
date: "2024-03-04"
date-modified: "2024-03-04"
draft: FALSE
---

Dataset 1:Weekly United States COVID-19 Racial Data By State, April 12, 2020 to March 7, 2021

URL: https://datadryad.org/stash/dataset/doi:10.7272/Q6TT4P68

The dataset contains 212,969 rows and 86 columns.The dataset in question originates from a joint effort by the COVID Tracking Project and Boston University's Center for Antiracist Research. It has been actively compiled since April 12, 2020, with updates being made twice weekly. The data is sourced from the official public health websites of various states and territories, with the collection process being carried out by volunteers, whose names have been provided. The dataset comprises 54 columns and includes 5320 data points. One notable limitation of the dataset is the inconsistency in reporting the ethnicity data across different states, particularly regarding the categorization of Hispanic or Latino races—some states include this data while others do not. There are 13 columns dedicated to documenting COVID-19 cases across different ethnicities, but there are redundancies, such as the columns for Cases_Latinx and Cases_Ethnicity_Hispanic, which appear to contain similar, if not identical, data. Additionally, the dataset includes 13 columns each for deaths, hospitalizations, and total cases, all disaggregated by ethnicity. However, these sections have many missing entries, which could pose challenges for data cleaning and further analysis.

Questions want to answer based on the dataset:
-Does the hospitalizations rate affect the deaths rate?
-Which ethnicity or group of ethnicities has the highest deaths rate?
- Is there a correlation between the hospitalization rate and the death rate due to COVID-19, and if so, how strong is this relationship?
-Does the hospitalization rate for COVID-19 differ significantly among ethnic groups, and what might this reveal about access to healthcare or disease severity?
- How have hospitalization and death rates evolved over time for each ethnicity, and are there noticeable trends or patterns?
- Are there regional variations in the death and hospitalization rates among different ethnicities, and what might this indicate about local public health policies?


Dataset 2: Ethnicity disparities in school in United States
URL: https://www.education-inequalities.org/countries/united-states
The dataset provided by the World Inequality Database on Education (WIDE) tracks educational disparities across various countries, including the United States. From the 212,969 rows and 86 columns, it provides data on education outcomes differentiated by wealth, gender, ethnicity, and location, among other factors. This database can be significant for analyzing racial disparities in education. Meanwhile, the dataset provides numerous variables such as income, region, and completions of education which enable us to perform variable selection to find the best variable to show the correlation between racial disparities and education. We will likely face difficulties while cleaning the data since the dataset is relatively large with numerous outliers.
Question want to answer based on the dataset:
-How do educational outcomes vary by region and demographic groups in the USA? 

-How have educational outcomes been affected by race in the dataset? 

Dataset 3: US Police Shootings
URL: https://www.kaggle.com/datasets/ahsen1330/us-police-shootings?resource=download
There are 4896 rows and 15 columns for this dataset. This data was collected from Kaggle amidst the covid 19 pandemic when many hate crimes directed towards specific races were happening.
The dataset is consisted of 4896 rows and 15 columns.One challenge that we may face with this dataset is that it is on the smaller side. 5,000 rows is not necessarily small, but it is definitely not large either. If we want to conduct a very reliable study, it may be worth considering finding a dataset with more rows. Another problem that we may run into is that it will be difficult to assess whether a police killing was justified or not if we do not have more description on the crime. For example, if there was a column that described how long the altercation lasted, it may provide more insight into whether or not the crime was justified. 

Questions want to answer based on the dataset:
-Does race and age play a factor in who gets killed by the police?
-How are the shooting crime related to the race and age group


